var _ = require('lodash');
var var1 = 'underscore_case';
var var2 = 'first_name';
var var3 = 'Some_Variable';
var var4 = 'Calculate_age';
var var5 = 'delay_departure';
console.log(_.camelCase(var1));
console.log(_.camelCase(var2));
console.log(_.camelCase(var3));
console.log(_.camelCase(var4));
console.log(_.camelCase(var5));
